### ISSUE TITLE
add singletons through add_autoload_singleton()

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/VisualNovelKit#100]
singletons are not added through `add_autoload_singleton()`

**Comment by theludovyc** [comment]
I take it o/

**Comment by theludovyc** [comment]
![image](https://user-images.githubusercontent.com/7337158/138552748-8fdc5d57-bb7a-425e-a35e-c5e8fe185c93.png)
Do you want to make add_autoload_singleton() on Window ? If yes, how ? :)

**Comment by Jeremi360** [comment]
> ![image](https://user-images.githubusercontent.com/7337158/138552748-8fdc5d57-bb7a-425e-a35e-c5e8fe185c93.png) Do you want to make add_autoload_singleton() on Window ? If yes, how ? :)

@theludovyc Yes and No, I want this to be added as singleton, but only for gui.
But we call `add_autoload_singleton()` only from **EditorPlugin**.
So I think now *Window* singleton should be a part of *project.godot* included in **BoundleVN**.

**Comment by theludovyc** [comment]
Ok 😊 ! So ready for review !

**Comment by Jeremi360** [comment]
> Ok 😊 ! So ready for review !

@theludovyc reviewed and merged 😄
