### ISSUE TITLE
is there a story script format

### ISSUE THREAD

**Issue by wanghaisheng** [rakugoteam/VisualNovelKit#121]
possible use case like 

I got a movie srt ,then I want to turn this srt into visualnovlekit script that tool can use,may be a litte adjustment needed 

I got a novel text  ,then I want to turn this txt into visualnovlekit script that tool can use,may be a litte adjustment needed

**Comment by Jeremi360** [comment]
@wanghaisheng I don't understand this proposal, can you explain it a bit more ?
Second, this is a proposal for a story script format? You mean dialogue scripting language?
Then you shouldn't propose it here, Visual Novel Kit is a Rakugo Kit h[ere is definition of this idea](https://rakugoteam.github.io/news/devlog/rakugo-3.3-devlog-02/#kits).
So this if you mean dialogue scripting language then it should be proposed at [Rakugo core repo](https://github.com/rakugoteam/Rakugo).
And yes I want to add dialogue scripting language, but there is only me and @theludovyc 
are working on this project right now, and we do it only in our free time.
But if you want and know GDScript you can join us to add it your self.
