### ISSUE TITLE
Broken "master" template download

### ISSUE THREAD

**Issue by michael-conrad** [rakugoteam/VisualNovelKit#30]
**Describe the bug**
Download and import of "master" per [https://rakugodocs.readthedocs.io/en/latest/topics/project_setup/#create-rakugo-project](https://rakugodocs.readthedocs.io/en/latest/topics/project_setup/#create-rakugo-project) results in a non-functioning copy of "The Question" and not a blank template project shell.

**To Reproduce**
Download the template
Import it.

**Expected behavior**
A blank ready to go project.

**Runtime (please complete the following information):**
 - Godot version: 3.2.4rc3
 - Rakugo Version: 3.1.1

**Comment by michael-conrad** [comment]
Getting: ```Invalid get index 'res://game/scenes/start.tscn' (on base: 'Dictionary').```

**Comment by Carpynch0** [comment]
missing scene start.tscn in scenelinks.

**Comment by Jeremi360** [comment]
Sorry about this I will fix this today. @michael-conrad @Carpynch0

**Comment by Jeremi360** [comment]
@michael-conrad @Carpynch0 Fixed just redownload.
