### ISSUE TITLE
Rakugo: The Question Godot 3.2 1.4.2

### ISSUE THREAD

**Issue by DowsingUK** [rakugoteam/VisualNovelKit#4]
I'm trying to download demo from Godot asset library but keep getting 404 not found error I've been looking everywhere but not luck where can I find it thank you so much for your great plugin 

https://github.com/rakugoteam/Rakugo/archive/98e9f9288cec0438bb2fe96c9e819e7956437b38.zip

**Comment by Jeremi360** [comment]
@DowsingUK Sorry, but updates in current version of asset lib take very long to process, so I give up with them for now.
Recently Rakugo was totally rewritten you can read about this here, there are also links to new version there as well.
https://jeremi360x.itch.io/rakugo/devlog/196912/about-the-upcoming-release-rakugo-300

**Comment by DowsingUK** [comment]
I have try to download the 3.0.0b but still getting the old version for the links you upload 17 hours ago

**Comment by Jeremi360** [comment]
@DowsingUK You misunderstand me, version from 17 hours ago is the newest one.

**Comment by DowsingUK** [comment]
Got it but how can I download it then?

**Comment by Jeremi360** [comment]
@DowsingUK okej I see now, I missed that you want to download *The Question* port.
Now all Rakugo stuff is on this repo, but just on different branches.
You can download  *The Question* port here: https://github.com/rakugoteam/Rakugo/archive/the-question.zip

**Comment by DowsingUK** [comment]
Yes that's right I want to download the version 3.0.0b but I keep getting version 2.0.0 even from this last link you send

**Comment by Jeremi360** [comment]
@DowsingUK Okej I see. I just forgot to change version string in ProjectSettings it is 3.0.0b

**Comment by DowsingUK** [comment]
Well I'm sure it's not only the ProjectSettings version

![Screen Shot 2020-12-03 at 3 20 43 PM](https://user-images.githubusercontent.com/60580139/101083961-459b7e80-357b-11eb-9909-2da6ee0b7ef8.png)

This is what I get when I build the project downloaded from the last link

**Comment by Jeremi360** [comment]
@DowsingUK It is, this is version of project not of rakugo it self.
If you go to Project estings plugins you will see this is right version:
![image](https://user-images.githubusercontent.com/1294815/101140306-133d6000-3613-11eb-8318-5d2ee8c04c39.png)
But Thanks I fix this this can be misleading.

**Comment by Jeremi360** [comment]
Fixed in #5 just redownload @DowsingUK
