### ISSUE TITLE
Unify the naming of files and dirs 

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/VisualNovelKit#85]
Now, some scripts files are using snake_case and other PascalCase.
As most are Nodes/Classes and Godot itself uses for those PascalCase then we also should.

@theludovyc fixed:
- [x] Unify the naming of scripts files

But I forgot 2 things:
- [x] node icons files they also should be PascalCased
- [x] dirs with scenes in it should be also PascalCased

- [x] fix naming in some missed files/dirs

**Comment by theludovyc** [comment]
Take it o/

**Comment by Jeremi360** [comment]
Comment that was here was added to description of issue,
 to make it, create subtasks for this issue.

**Comment by Jeremi360** [comment]
It was fixed, but **Git for Windows** didn't get all changes for @theludovyc
