### ISSUE TITLE
Rakugo Plugins ??

### ISSUE THREAD

**Issue by Jeremi360** [rakugoteam/VisualNovelKit#87]
We should add some way so we or other devs can made Rakugo or Godot and Rakugo plugins.
- [x] #88
- [x] #89
```gdscript
tool
extends EditorPlugin

var rakugo_enabled := false

func _enter_tree():
# Check if Rakugo is enabled
var plugins : Array = ProjectSettings.get_setting("editor_plugins/enabled")
rakugo_enabled := "res://addons/Rakugo/plugin.cfg" in plugins

if rakugo_enabled:
  return

## Godot init plugin only stuff here

func rakugo_on(rakugo_args): # rakugo_args - maybe a rakugo menu 
## Rakugo init plugin only stuff here

func _exit_tree():
if rakugo_enabled:
  return

## Godot disable plugin only stuff here

func rakugo_off(rakugo_args): # rakugo_args - maybe a rakugo menu 
## Rakugo disable only stuff here
```

**Comment by theludovyc** [comment]
Hello :)

Why you do that ?

```gdscript
var rakugo_enabled := false

func _enter_tree():
# Check if Rakugo is enabled
var plugins : Array = ProjectSettings.get_setting("editor_plugins/enabled")
rakugo_enabled := "res://addons/Rakugo/plugin.cfg" in plugins

if rakugo_enabled:
  return
```

**Comment by Jeremi360** [comment]
> Hello :)
> 
> Why you do that ?
> 
> ```gdscript
> var rakugo_enabled := false
> 
> func _enter_tree():
> # Check if Rakugo is enabled
> var plugins : Array = ProjectSettings.get_setting("editor_plugins/enabled")
> rakugo_enabled := "res://addons/Rakugo/plugin.cfg" in plugins
> 
> if rakugo_enabled:
>   return
> ```
@theludovyc 
This is an example of `plugin.gd` in plugin for Rakugo.
I was thinking about some way that allow to have addon for both godot and rakugo with simple change in *plugin.gd*.
After `if rakugo_enabled: return` there would be normal godot plugin init code or nothing if this is only Rakugo plugin.
`rakugo_on()` and `rakugo_off()` would be called by *Rakugo/plugin.gd*.

**Comment by theludovyc** [comment]
You have this
![image](https://user-images.githubusercontent.com/7337158/138550725-850804e1-9e56-451b-b657-cbab8105891b.png)
And if rakugo is not enabled and you have plugin on it, they crash and are not load :)

**Comment by Jeremi360** [comment]
> You have this ![image](https://user-images.githubusercontent.com/7337158/138550725-850804e1-9e56-451b-b657-cbab8105891b.png) And if rakugo is not enabled and you have plugin on it, they crash and are not load :)

@theludovyc Yes I know, now when I'm thinking about this I see this not needed. So I close this.
